### ISSUE TITLE
Responsive - Facilities Inner pages - Pure Yoga Rooms thumbnail is aligning weird. Please see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/On-Edge-Fitness#27]
![screen shot 2018-03-08 at 11 36 56 am](https://user-images.githubusercontent.com/8631079/37163221-33cd4b50-22c5-11e8-8ea7-c3d37bd25d2f.png)

**Comment by ccmorris** [comment]
Alignment issues fixed in #26
